language: java

script: ./gradlew build jacocoTestReport

jdk:
  - oraclejdk8

# Cache local Maven repository.
cache:
  directories:
    - $HOME/.m2
before_cache:
  - rm -Rf $HOME/.m2/repository/com/github/vineey/archelix-rsql

before_install:
 - chmod +x gradlew

after_success:
 - ./gradlew jacocoRootReport coveralls